{
 "title": "Server / Load Monitoring Thick",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node / Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)",
       "legendFormat": "ready"
      },
      {
       "expr": "sum(kube_node_status_condition{condition!=\"Ready\", status=\"true\"})",
       "legendFormat": "non_ready"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
       "legendFormat": "capacity"
      },
      { "expr": "sum(kube_pod_info)", "legendFormat": "pods" },
      {
       "expr": "sum(kube_pod_info{namespace!=\"server\"})",
       "legendFormat": "baseline"
      }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Currently Running Pods",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count ( kube_pod_container_status_running{namespace=~\"load|server\"}) by ( namespace ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(caller_sent_calls[$__range]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "Successful Calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(caller_sent_calls_successful[$__range])) / sum(rate(caller_sent_calls[$__range]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "avg req",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(server_processed_calls{namespace=\"server\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"server\"}"
    }
   ]
  },
  {
   "title": "updating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"server\"} - kube_deployment_status_replicas_unavailable{namespace=\"server\"} - kube_deployment_status_replicas_available{namespace=\"server\"}"
    }
   ]
  },
  {
   "title": "unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"server\"}"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(caller_sent_calls[$__range]))"
      },
      {
       "expr": "sum(rate(caller_sent_calls_failed[$__range]))"
      },
      {
       "expr": "sum(rate(caller_sent_calls_successful[$__range]))"
      }
     ]
    },
    {
     "title": "Call Duration .95 Quantile",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(caller_duration_calls_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Calls Percentage in last 5 minutes",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg ( \nrate(\n    caller_sent_calls_successful{namespace=\"load\"}[5m]\n)/ \nrate(\n    caller_sent_calls{namespace='load'}[5m]\n)\n) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Calls Percentage in last 30 seconds",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg ( \nrate(\n    caller_sent_calls_successful{namespace=\"load\"}[30s]\n)/ \nrate(\n    caller_sent_calls{namespace='load'}[30s]\n)\n) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg(rate(server_processed_calls[$__range]))"
      }
     ]
    },
    {
     "title": "Requests Processed Rate per Server Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(server_processed_calls{namespace=\"server\"}[20s])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}