{
 "title": "Server / Load Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Currently Running Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count ( kube_pod_container_status_running{namespace=~\"load|server\"}) by ( namespace )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Calls Percentage in last 5 minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ( \nrate(\n    caller_sent_calls_successful{namespace=\"load\"}[5m]\n)/ \nrate(\n    caller_sent_calls{namespace='load'}[5m]\n)\n) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Calls Percentage in last 30 seconds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ( \nrate(\n    caller_sent_calls_successful{namespace=\"load\"}[30s]\n)/ \nrate(\n    caller_sent_calls{namespace='load'}[30s]\n)\n) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Duration .95 Quantile",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(caller_duration_calls_bucket[20s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Processed Rate per Server Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(server_processed_calls{namespace=\"server\"}[20s])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}